import {getChatGPTUser} from '@/app/chatgpt-auth';
import {db,seal,unseal,runtime} from '@/lib/primtal/store';
import {amb} from '@/lib/primtal/ambiguous';
import {z} from 'zod';
export const dynamic='force-dynamic';
type Connection={botKey:string;openrouterKey:string;botId:string;workspaceId:string;botName:string;checkedAt:string};
async function authorized(request:Request){const user=await getChatGPTUser();if(!user)throw new Error('Sign in required');if(request.method==='POST'&&request.headers.get('origin')!==new URL(request.url).origin)throw new Error('Open this form from your Primtal page');const existing=await db().prepare('SELECT owner,value FROM settings WHERE id=?').bind('connections').first<{owner:string;value:string}>();if(existing&&existing.owner!==user.userId)throw new Error('Only the connection owner can manage provider keys');return {user,existing};}
const safe=(message:string,status=400)=>Response.json({error:message},{status,headers:{'Cache-Control':'no-store'}});
export async function GET(request:Request){try{const {existing}=await authorized(request);const c=existing?await unseal<Connection>(existing.value):null;return Response.json({saved:!!c,botKeyAvailable:!!c?.botKey||!!runtime('AMBIGUOUS_BOT_TOKEN'),botName:c?.botName||null,checkedAt:c?.checkedAt||null},{headers:{'Cache-Control':'no-store'}});}catch{return safe('Sign in with the owner account to manage connections.',403);}}
export async function POST(request:Request){try{const {user,existing}=await authorized(request);const input=z.object({botKey:z.string().max(1000).optional(),openrouterKey:z.string().min(10).max(1000),consent:z.literal(true)}).strict().parse(await request.json());const old=existing?await unseal<Connection>(existing.value):null;const botKey=input.botKey?.trim()||old?.botKey||runtime('AMBIGUOUS_BOT_TOKEN');if(!botKey)return safe('Enter the Ambiguous agent API key.');let bot;try{bot=await amb(botKey,'/api/users/me');}catch{return safe('Ambiguous could not validate that key. Check the agent key and try again.');}if(bot.type!=='agent'||!bot.id||!bot.workspace_id)return safe('Use the API key for an Ambiguous agent in your workspace.');let r;try{r=await fetch('https://openrouter.ai/api/v1/key',{headers:{Authorization:`Bearer ${input.openrouterKey.trim()}`},signal:AbortSignal.timeout(12000)});}catch{return safe('OpenRouter could not be reached. Try again.');}if(!r.ok)return safe('OpenRouter rejected that key. Check it and try again.');const data:Connection={botKey,openrouterKey:input.openrouterKey.trim(),botId:bot.id,workspaceId:bot.workspace_id,botName:bot.display_name,checkedAt:new Date().toISOString()};await db().prepare('INSERT INTO settings(id,owner,value) VALUES(?,?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value WHERE settings.owner=excluded.owner').bind('connections',user.userId,await seal(data)).run();return Response.json({saved:true,botName:data.botName,checkedAt:data.checkedAt},{headers:{'Cache-Control':'no-store'}});}catch{return safe('Could not save the connection. Check both keys, consent and your sign-in.');}}
