import {z} from 'zod';
import type {Config} from './store';
export class AmbiguousError extends Error {constructor(public status:number){super(status===401?'Ambiguous rejected this API key (401). Use the saved agent key or a new agent API key.':status===403?'The Ambiguous agent lacks permission for this operation (403).':`Ambiguous returned HTTP ${status}. Try again shortly.`);}}
export async function amb(key:string,path:string,method='GET',body?:unknown){let r:Response;try{r=await fetch('https://app.ambiguous.ai'+path,{method,headers:{Authorization:`Bearer ${key.trim()}`,'Content-Type':'application/json','API-Version':'1'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(25000)});}catch{throw new Error('Ambiguous did not respond in time. Your key has not been rejected; try again.');}if(!r.ok)throw new AmbiguousError(r.status);if(r.status===204)return {};return z.record(z.any()).parse(await r.json());}
export async function assertDM(c:Config){const d=await amb(c.botKey,`/api/channels/${c.channelId}`);const ids=(d.members||[]).map((m:{user_id:string})=>m.user_id);if(d.type!=='dm'||ids.length!==2||!ids.includes(c.userId)||!ids.includes(c.botId))throw new Error('Delivery stopped: this must be a one-to-one DM with your Primtal bot.');}
export async function send(c:Config,text:string){await assertDM(c);return amb(c.botKey,`/api/channels/${c.channelId}/messages`,'POST',{content:text,starts_new_block:true});}
export async function ownCalendar(c:Config){const r=await amb(c.botKey,'/api/calendars');const owned=(r.data||[]).filter((x:{id:string;owner_id:string;workspace_id:string})=>x.owner_id===c.userId&&x.workspace_id===c.workspaceId);if(c.calendarId){if(!owned.some((x:{id:string})=>x.id===c.calendarId))throw new Error('Share your selected personal calendar with Primtal.');return c.calendarId;}if(owned.length!==1)throw new Error(owned.length?'Choose one of your calendars in the Primtal panel.':'Share your personal calendar with Primtal.');c.calendarId=owned[0].id;return c.calendarId;}
export type Event={id:string;calendar_id:string;start_at:string;end_at:string;title:string;description?:string;status:string;transparency:string;all_day?:boolean;color?:string|null;creator_id?:string|null;updated_at?:string|null;recurrence_rule?:string|null;master_event_id?:string|null;external_id?:string|null;is_task?:boolean;has_more_attendees?:boolean;attendees?:{user_id?:string;email?:string}[];resources?:unknown[]};
export async function events(c:Config,start:string,end:string){const calendars=await amb(c.botKey,'/api/calendars');if(!calendars.data?.some((x:{id:string;owner_id:string})=>x.id===c.calendarId&&x.owner_id===c.userId))throw new Error('Share your personal calendar with Primtal, then select it in Connections.');let out:Event[]=[];let cursor='';for(let i=0;i<20;i++){const p=new URLSearchParams({calendar_id:c.calendarId,start,end,singleEvents:'true',limit:'100',...(cursor?{cursor}:{})});const r=await amb(c.botKey,`/api/calendars/events?${p}`);out.push(...r.data);if(!r.has_more)return out.filter(x=>x.calendar_id===c.calendarId&&x.status!=='cancelled'&&x.transparency!=='transparent');if(!r.next_cursor)throw new Error('Calendar pagination incomplete');cursor=r.next_cursor;}throw new Error('Calendar contains too many events to analyze safely');}
