import {db,seal,unseal,hash,type Config} from './store';
import {providers} from './connections';
export type Person=Omit<Config,'botKey'|'openrouterKey'|'model'|'botId'|'workspaceId'> & {workspaceId:string;cursor?:string;joined:number;name?:string};
export const personId=(workspace:string,user:string)=>`amb:${workspace}:${user}`;
export async function person(id:string){const r=await db().prepare('SELECT value FROM participants WHERE id=?').bind(id).first<{value:string}>();return r?unseal<Person>(r.value):null;}
export async function savePerson(id:string,p:Person){await db().prepare('INSERT INTO participants(id,workspace_id,user_id,value) VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind(id,p.workspaceId,p.userId,await seal(p)).run();}
export async function personConfig(id:string):Promise<Config>{const [p,c]=await Promise.all([person(id),providers()]);if(!p||p.workspaceId!==c.workspaceId)throw new Error('Pair your Ambiguous account first.');return {...p,...c};}
export async function bound(owner:string){const r=await db().prepare('SELECT participant_id FROM bindings WHERE owner=?').bind(owner).first<{participant_id:string}>();return r?.participant_id||null;}
export async function pairing(owner:string){if(await bound(owner))throw new Error('Your Ambiguous account is already paired.');const code=Array.from(crypto.getRandomValues(new Uint8Array(8)),v=>v.toString(16).padStart(2,'0')).join('').toUpperCase();await db().prepare('INSERT INTO pairings(owner,code_hash,expires) VALUES(?,?,?) ON CONFLICT(owner) DO UPDATE SET code_hash=excluded.code_hash,expires=excluded.expires').bind(owner,await hash(code),Date.now()+600000).run();return {command:`PAIR ${code}`,expires:new Date(Date.now()+600000).toISOString()};}
export async function completePairing(code:string,id:string){const row=await db().prepare('SELECT owner FROM pairings WHERE code_hash=? AND expires>?').bind(await hash(code.toUpperCase()),Date.now()).first<{owner:string}>();if(!row)return false;await db().batch([db().prepare('INSERT INTO bindings(owner,participant_id) VALUES(?,?) ON CONFLICT(owner) DO NOTHING').bind(row.owner,id),db().prepare('DELETE FROM pairings WHERE owner=?').bind(row.owner)]);return (await bound(row.owner))===id;}
