import { env } from 'cloudflare:workers';
import {getChatGPTUser} from '@/app/chatgpt-auth';
export const db=()=>{if(!env.DB) throw new Error('Storage unavailable');return env.DB;};
export function runtime(name:string){return (env as unknown as Record<string,string>)[name]||'';}
export async function seal(value:unknown){const raw=runtime('PRIMTAL_ENCRYPTION_KEY');if(!raw)throw new Error('Encryption is not configured');const key=await crypto.subtle.importKey('raw',Uint8Array.from(atob(raw),c=>c.charCodeAt(0)),'AES-GCM',false,['encrypt']);const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv},key,new TextEncoder().encode(JSON.stringify(value)));return btoa(String.fromCharCode(...iv,...new Uint8Array(data)));}
export async function unseal<T>(value:string):Promise<T>{const bytes=Uint8Array.from(atob(value),c=>c.charCodeAt(0));const key=await crypto.subtle.importKey('raw',Uint8Array.from(atob(runtime('PRIMTAL_ENCRYPTION_KEY')),c=>c.charCodeAt(0)),'AES-GCM',false,['decrypt']);return JSON.parse(new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:bytes.slice(0,12)},key,bytes.slice(12))));}
export type Config={botKey:string;openrouterKey:string;model:string;botId:string;workspaceId:string;userId:string;channelId:string;calendarId:string;timezone:string;hour:string;enabled:boolean;consent:boolean;automationId?:string;lastDay?:string;remoteHash?:string;support:string};
export async function config(){const row=await db().prepare('SELECT owner,value FROM settings WHERE id=?').bind('primtal').first<{owner:string,value:string}>();return row?{owner:row.owner,data:await unseal<Config>(row.value)}:null;}
export async function saveConfig(id:string,data:Config){const {savePerson,person}=await import('./participants');const existing=await person(id);if(!existing)throw new Error('Participant is not paired');const {botKey,openrouterKey,model,botId,...value}=data;await savePerson(id,{...existing,...value});}
export async function owner(request?:Request){if(request&&request.method!=='GET'){const origin=request.headers.get('origin');if(origin&&origin!==new URL(request.url).origin)throw new Error('Cross-origin request denied');}const u=await getChatGPTUser();if(!u)throw new Error('Sign in required');const c=await config();if(c&&c.owner!==u.userId)throw new Error('This personal workspace belongs to another user');return u.userId;}
export async function lock<T>(id:string,work:()=>Promise<T>):Promise<T>{const token=crypto.randomUUID();const now=Date.now();const r=await db().prepare('INSERT INTO locks (id,token,expires) VALUES (?,?,?) ON CONFLICT(id) DO UPDATE SET token=excluded.token, expires=excluded.expires WHERE locks.expires < ?').bind(id,token,now+180000,now).run();if(!r.meta.changes)throw new Error('A request is already running. Wait a moment.');try{return await work();}finally{await db().prepare('DELETE FROM locks WHERE id=? AND token=?').bind(id,token).run();}}
export async function hash(s:string){return Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(v=>v.toString(16).padStart(2,'0')).join('');}
export function errorResponse(e:unknown){return Response.json({error:e instanceof Error?e.message:'Request failed'}, {status:400,headers:{'Cache-Control':'no-store'}});}
