import {messageText} from './message-text';
import {formatInTimeZone,fromZonedTime} from 'date-fns-tz';
import {questions,normalize,promptQuestion,questionTitle,domainNames,firstName,type Domain} from './questions';
import {db,seal,unseal,saveConfig,type Config} from './store';
import {amb,assertDM,send,events,ownCalendar,type Event} from './ambiguous';
import {classify,supportMessage} from './openrouter';
import {screeners,screenPrompt,screenResult} from './screeners';
import {deliverCard,selectedChoice,closeCard,type Choice,type Outbox} from './message-cards';
import {SYSTEM_EVENT_COLOR,applied,workingSlot,meetingProposal,changeMeeting,type CalendarProposal} from './calendar-actions';
import {patternHistory,lateMeetingPattern} from './patterns';
export type Session={id:string;owner:string;day:string;demo:boolean;stage:string;index:number;answers:Record<string,number>;note?:string;safety?:string;queue:string[];screen?:string;screenAnswers:number[];screenResults:Record<string,unknown>;cursor?:string;created:number;summary?:string;proposal?:CalendarProposal;focus?:CalendarProposal;source?:'synthetic';outbox?:Outbox;error?:string;name?:string;calendarReviewed?:boolean};
export async function getSession(owner:string){const r=await db().prepare('SELECT value FROM sessions WHERE id=? AND owner=?').bind(owner,owner).first<{value:string}>();return r?unseal<Session>(r.value):null;}
export async function persist(s:Session){await db().prepare('INSERT INTO sessions (id,owner,value,updated) VALUES (?,?,?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value,updated=excluded.updated WHERE sessions.owner=excluded.owner').bind(s.owner,s.owner,await seal(s),Date.now()).run();}
async function queue(s:Session,content:string,choices?:Choice[],question?:string){s.outbox={content,choices,question,ref:crypto.randomUUID(),created:Date.now(),state:'pending'};await persist(s);}
async function dailyCard(s:Session){const q=questions[s.index];await queue(s,'',Object.entries(q.scale_labels).map(([value,label])=>({label,value})),questionTitle(s.index,s.name));}
function followupChoices(s:Session):Choice[]{return [...(s.queue.length?[{label:'Optional follow-up',value:'FOLLOWUP'}]:[]),{label:'Finish for today',value:'DONE'}];}
export async function flush(c:Config,s:Session){await deliverCard(c,s,persist);}
export async function offerConsent(owner:string,c:Config){
 await assertDM(c);const old=await getSession(owner);if(old?.stage==='consent'){await flush(c,old);return old;}
 const s:Session={id:crypto.randomUUID(),owner,day:formatInTimeZone(new Date(),c.timezone,'yyyy-MM-dd'),demo:false,stage:'consent',index:0,answers:{},queue:[],screenAnswers:[],screenResults:{},created:Date.now(),name:c.name};
 await queue(s,`**Hello, ${firstName(c.name)} 👋**\nI'm Primtal. Let's make a little room for your wellbeing.\n\nWith your agreement, I save your answers privately, process optional notes through OpenRouter, and read the personal calendar you share with me. Calendar changes always need your confirmation.`,[{label:'AGREE',value:'AGREE'},{label:'Maybe later',value:'LATER'}],'Ready for your first check-in?');await flush(c,s);return s;
}
export async function start(owner:string,c:Config,demo:boolean){if(!c.consent)throw new Error('Confirm personal-data consent first.');await assertDM(c);const old=await getSession(owner);if(old&&!['complete','stopped','safety','approved'].includes(old.stage)){await flush(c,old);return old;}const day=formatInTimeZone(new Date(),c.timezone,'yyyy-MM-dd');if(!demo&&old?.day===day&&!old.demo)return old;const s:Session={id:crypto.randomUUID(),owner,day,demo,stage:'daily',index:0,answers:{},queue:[],screenAnswers:[],screenResults:{},created:Date.now(),name:c.name};await dailyCard(s);await flush(c,s);return s;}
async function history(owner:string,day:string,demo:boolean){const first=new Date(day+'T12:00:00Z');first.setUTCDate(first.getUTCDate()-7);const rows=await db().prepare('SELECT value FROM checkins WHERE owner=? AND demo=? AND day>=? AND day<? ORDER BY day').bind(owner,demo?1:0,first.toISOString().slice(0,10),day).all<{value:string}>();return (await Promise.all(rows.results.map(r=>unseal<Session>(r.value)))).filter(r=>r.source!=='synthetic');}
async function saveCheckin(s:Session){await db().prepare('INSERT INTO checkins(id,owner,day,demo,value) VALUES(?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET value=excluded.value').bind(`${s.owner}:${s.demo?'demo':'real'}:${s.day}`,s.owner,s.day,s.demo?1:0,await seal({...s,outbox:undefined})).run();}
function dayBounds(day:string,tz:string){return {start:fromZonedTime(day+'T00:00:00',tz).toISOString(),end:fromZonedTime(day+'T23:59:59.999',tz).toISOString()};}
export function occupiedMinutes(es:Event[],start:number,end:number){const ranges=es.map(e=>[Math.max(start,Date.parse(e.start_at)),Math.min(end,Date.parse(e.end_at))]).filter(([a,b])=>b>a).sort((a,b)=>a[0]-b[0]);let total=0,lastStart=0,lastEnd=0;for(const [a,b] of ranges){if(a>lastEnd){total+=lastEnd-lastStart;lastStart=a;lastEnd=b;}else lastEnd=Math.max(lastEnd,b);}return Math.round((total+lastEnd-lastStart)/60000);}
export async function analyze(c:Config,s:Session){
 if(s.index!==6||s.safety&&s.safety!=='clear')throw new Error('Complete a clear check-in before calendar review.');
 if(s.proposal&&['uncertain','creating','moving','undoing'].includes(s.proposal.status))throw new Error('A previous calendar change is unconfirmed. Inspect the event before making another change.');
 const focus=s.proposal?.status==='created'&&s.proposal.kind!=='move'?s.proposal:s.focus?.status==='created'?s.focus:undefined;
 if(focus)s.focus=focus;const completedMove=s.proposal?.kind==='move'&&s.proposal.status==='moved'?s.proposal:undefined;
 await closeCard(c,s.outbox);await saveCheckin(s);
 const answers=questions.map(q=>`| ${domainNames[q.construct]} | ${q.scale_labels[String(s.answers[q.construct]) as '1'|'2'|'3'|'4'|'5']} |`).join('\n');
 try{
  await ownCalendar(c);await saveConfig(s.owner,c);const bounds=dayBounds(s.day,c.timezone);const first=new Date(s.day+'T12:00Z');first.setUTCDate(first.getUTCDate()-28);
  const [today,prior,past,upcoming]=await Promise.all([events(c,bounds.start,bounds.end),patternHistory(s.owner,s.day),events(c,dayBounds(first.toISOString().slice(0,10),c.timezone).start,bounds.start),events(c,new Date().toISOString(),new Date(Date.now()+8*86400000).toISOString())]);
  const pattern=lateMeetingPattern(prior,past,c.timezone);const move=pattern.matched&&!completedMove?await meetingProposal(c,today,upcoming):null;
  const free=workingSlot(upcoming,c.timezone,60,Date.now(),today.length>0);
  const proposal:CalendarProposal|undefined=completedMove||move||focus||(free?{kind:'focus',...free,status:'pending'}:undefined);
  s.proposal=proposal;s.stage=applied(proposal)?'approved':proposal?'proposal':'complete';s.calendarReviewed=true;delete s.error;
  const range=(p:{start:string;end:string})=>`${formatInTimeZone(p.start,c.timezone,'EEE d MMM, HH:mm')}–${formatInTimeZone(p.end,c.timezone,'HH:mm')}`;
  s.summary=`🌿 **${firstName(c.name)}, here is your day.**\n\n| Check-in | Your answer |\n| --- | --- |\n${answers}\n\n**Your calendar today**\n**${today.length} busy events · ${occupiedMinutes(today,Date.parse(bounds.start),Date.parse(bounds.end))} occupied minutes**\nOverlaps counted once. Includes personal blocks.\n\n${pattern.text}`;
  if(focus)s.summary+=`\n\n**Your focus hour is protected:** ${range(focus)}. [Open focus event](https://app.ambiguous.ai/calendar?event=${focus.eventId})`;
  let content=s.summary,choices:Choice[]|undefined,question='Your check-in is saved';
  if(proposal?.kind==='move'&&proposal.status==='pending'){
   content+=`\n\n**A similar late meeting appears today: ${proposal.title}.**\nCurrent: ${range(proposal.original!)}.\nSuggested: **${range(proposal)} (${c.timezone})**.\nMove this meeting into working hours? Its duration stays the same. Only your personal event changes; no invitations are sent.`;
   choices=[{label:'Move to working hours',value:'MOVE'},{label:'Keep this meeting',value:'SKIP'}];question=`📅 ${range(proposal)} · Move this meeting?`;
  }else if(proposal?.status==='moved'){
   content+=`\n\n**Meeting moved:** ${proposal.title} · ${range(proposal)}. [Open meeting](https://app.ambiguous.ai/calendar?event=${proposal.eventId})`;
   choices=[{label:'Restore original time',value:'UNDO'},...followupChoices(s)];question='✓ Meeting moved';
  }else if(proposal?.status==='created'){
   choices=[{label:'Undo this focus block',value:'UNDO'},...followupChoices(s)];question='✓ Focus time protected';
  }else if(proposal){
   content+=`\n\nAvailable: **${range(proposal)} (${c.timezone})**. Would a protected hour help? Choose Protect this hour to create a calendar event. No invitations will be sent.`;
   choices=[{label:'Protect this hour',value:'APPROVE'},{label:'Keep my calendar',value:'SKIP'}];question=`📅 ${range(proposal)} · Protect this hour?`;
  }else{content+='\n\nAn available hour could not be found in the next seven days.';if(s.queue.length)choices=followupChoices(s);}
  await queue(s,content,choices,question);await saveCheckin(s);
 }catch(e){s.stage='complete';s.error=e instanceof Error?e.message:'Calendar unavailable';await queue(s,`**${firstName(c.name)}, your check-in is saved.**\n\n| Check-in | Your answer |\n| --- | --- |\n${answers}\n\n**Calendar needs attention**\n${s.error}`, [{label:'Retry calendar',value:'CALENDAR'},{label:'Finish for today',value:'DONE'}],'📅 Review your calendar');}
}
async function nextScreen(c:Config,s:Session){const next=s.queue.shift();if(!next){if(s.calendarReviewed){s.stage=applied(s.proposal)?'approved':'complete';await queue(s,'Your follow-up is saved. Thank you for making time for yourself.');}else await analyze(c,s);return;}s.screen=next;s.screenAnswers=[];const screen=screeners[next];if(!screen){s.stage='screen-unavailable';s.screenResults[next]=`${next}: follow-up unavailable; no score generated.`;await queue(s,`Your ${next==='adhd'?'focus':next} response suggests difficulty. The full questionnaire is currently unavailable. No screening score or diagnosis was generated. Choose Continue to skip this follow-up.`,[{label:'Continue',value:'SKIP'},{label:'Stop',value:'STOP'}],'Optional follow-up');return;}s.stage='screen-offer';await queue(s,`Your ${next==='adhd'?'focus':next} response suggests some difficulty. Would you like to complete ${screen.name} for more context?\n\n${screen.recall}\nThis is a screening tool, not a diagnosis.`,[{label:'Begin optional check',value:'YES'},{label:'Skip follow-up',value:'SKIP'}],'A little more context?');}
async function screenCard(s:Session){const def=screeners[s.screen!];const content=`**${def.name} · ${s.screenAnswers.length+1}/${def.items.length}**\n${def.recall}\n\n${def.items[s.screenAnswers.length]}\n\nChoose one option below.`;await queue(s,content,Array.from({length:def.max-def.min+1},(_,i)=>({label:def.labels[i],value:String(i+def.min)})),`${def.name} · ${s.screenAnswers.length+1}/${def.items.length}`);}
export async function accept(c:Config,s:Session,text:string){const clean=messageText(text);const command=clean.toUpperCase();if(s.stage==='consent'){
 if(command==='LATER'||command==='STOP'){s.stage='stopped';c.enabled=false;await saveConfig(s.owner,c);await queue(s,'Whenever you are ready, send Hello.');return;}
 if(!['AGREE','I AGREE','I AGREE DEMO'].includes(command)){await queue(s,'Choose AGREE to begin, or Maybe later.',[{label:'AGREE',value:'AGREE'},{label:'Maybe later',value:'LATER'}],'Your choice');return;}
 c.consent=true;await ownCalendar(c).catch(()=>{});await saveConfig(s.owner,c);s.stage='daily';await dailyCard(s);return;
}if(command==='CALENDAR'){if(s.index!==6||s.safety&&s.safety!=='clear')throw new Error('Complete a check-in before calendar review.');await analyze(c,s);return;}if(command==='FOLLOWUP'&&s.calendarReviewed&&s.queue.length){await nextScreen(c,s);return;}if(command==='DONE'){s.stage=applied(s.proposal)?'approved':'complete';await queue(s,`Take care, ${firstName(c.name)}. Your check-in is saved.`);return;}if(command==='ADDNOTE'&&s.stage==='note'){await queue(s,'Write a short note about today, or send SKIP to continue.');return;}if(s.stage==='note'&&command!=='SKIP')s.note=clean.slice(0,4000);if(command==='UNDO'&&applied(s.proposal)){await undo(c,s);return;}if(command==='STOP'){c.enabled=false;await saveConfig(s.owner,c);s.stage='stopped';await queue(s,'Check-in stopped. You can start again from the Primtal panel.');return;}if(!/^[0-5]$/.test(clean)&&!['YES','SKIP','APPROVE','UNDO','START','CHECKIN','DEMO','FOLLOWUP','DONE','CALENDAR','ADDNOTE','MOVE'].includes(command)){const safety=await classify(c,clean);if(safety!=='clear'){s.safety=safety;s.stage='safety';s.proposal=undefined;await saveCheckin(s);await queue(s,(safety==='uncertain'?'I couldn’t reliably assess this note, so I’m pausing calendar actions.\n\n':'')+supportMessage+(c.support?'\n\n'+c.support:''));return;}}
if(s.stage==='daily'){if(!/^[1-5]$/.test(clean)){await dailyCard(s);return;}s.answers[questions[s.index].construct]=Number(clean);s.index++;if(s.index<questions.length){await dailyCard(s);return;}s.stage='note';await queue(s,`**All six answered, ${firstName(c.name)}.**\nWant to add context before we look at your calendar? Your optional note is checked through OpenRouter.`,[{label:'Add a short note',value:'ADDNOTE'},{label:'Continue to my calendar',value:'SKIP'}],'🌿 Anything you want to share?');return;}
if(s.stage==='note'){s.note=command==='SKIP'?'':clean;s.safety='clear';const prior=await history(s.owner,s.day,s.demo);s.queue=questions.filter(q=>q.construct!=='mood').filter(q=>normalize(q.construct,s.answers[q.construct])==='concern'||(normalize(q.construct,s.answers[q.construct])==='watch'&&prior.filter(p=>p.answers[q.construct]&&normalize(q.construct,p.answers[q.construct])!=='good').length>=2)).map(q=>q.construct);await saveCheckin(s);await analyze(c,s);return;}
if(s.stage==='screen-unavailable'){if(command==='SKIP')await nextScreen(c,s);else await queue(s,'Reply SKIP to continue without this unavailable questionnaire, or STOP.');return;}if(s.stage==='screen-offer'){if(command==='SKIP'){s.screenResults[s.screen!]='Follow-up declined: '+screeners[s.screen!].name;await nextScreen(c,s);return;}if(command!=='YES'){await queue(s,'Reply YES to begin the follow-up, or SKIP.');return;}s.stage='screen';await screenCard(s);return;}
if(s.stage==='screen'){const def=screeners[s.screen!];if(!/^\d$/.test(clean)||Number(clean)<def.min||Number(clean)>def.max){await screenCard(s);return;}s.screenAnswers.push(Number(clean));if(s.screen==='depression'&&s.screenAnswers.length===9&&Number(clean)>0){s.stage='safety';s.safety='flagged';s.screenResults[s.screen]=screenResult(s.screen,s.screenAnswers);await saveCheckin(s);await queue(s,supportMessage+(c.support?'\n\n'+c.support:''));return;}if(s.screenAnswers.length<def.items.length){await screenCard(s);return;}s.screenResults[s.screen!]=screenResult(s.screen!,s.screenAnswers);await nextScreen(c,s);return;}
if(s.stage==='proposal'&&s.proposal?.kind==='move'&&command!=='SKIP'){
 const p=s.proposal;if(command!=='MOVE'){await queue(s,'Choose whether to move the proposed meeting.',[{label:'Move to working hours',value:'MOVE'},{label:'Keep this meeting',value:'SKIP'}],'📅 Your meeting');return;}
 if(p.status!=='pending')throw new Error('This change was already attempted. Inspect the calendar before retrying.');
 try{await changeMeeting(c,p,false,async()=>{p.status='moving';await persist(s);});p.status='moved';s.stage='approved';await queue(s,`**Meeting moved, ${firstName(c.name)}.**\n${p.title}\n${formatInTimeZone(p.start,c.timezone,'EEE d MMM, HH:mm')}–${formatInTimeZone(p.end,c.timezone,'HH:mm')} (${c.timezone}).\n[Open meeting](https://app.ambiguous.ai/calendar?event=${p.eventId})\n\nPurple marks changes made with Primtal.`,[{label:'Restore original time',value:'UNDO'},...followupChoices(s)],'✓ Meeting moved');await saveCheckin(s);}
 catch(e){if(p.status==='moving')p.status='uncertain';await queue(s,(p.status==='uncertain'?'The calendar response was interrupted. Inspect the event before retrying.':e instanceof Error?e.message:'Meeting could not be moved.'),[{label:'Review calendar',value:'CALENDAR'},{label:'Finish for today',value:'DONE'}],'📅 Check your meeting');}return;
}
if(s.stage==='proposal'){if(command==='SKIP'){s.stage='complete';await queue(s,`Your calendar stays as it is, ${firstName(c.name)}. Your check-in is saved.`,s.queue.length?followupChoices(s):undefined,'Anything else for today?');return;}if(command!=='APPROVE'){await queue(s,'Reply APPROVE to create the proposed hour, or SKIP.');return;}const p=s.proposal!;if(Date.parse(p.start)<Date.now()){s.stage='complete';await queue(s,'That time has passed. No event was created. Please start a new check-in.');return;}const conflicts=await events(c,p.start,p.end);if(conflicts.some(e=>Date.parse(e.start_at)<Date.parse(p.end)&&Date.parse(e.end_at)>Date.parse(p.start))){s.stage='complete';await queue(s,'That hour is no longer free. No event was created.');return;}if(p.status!=='pending')throw new Error('Event creation already attempted; inspect the calendar before retrying.');p.status='creating';await persist(s);let created;try{created=await amb(c.botKey,`/api/calendars/${c.calendarId}/events`,'POST',{title:'Primtal · Focus time',color:SYSTEM_EVENT_COLOR,start_at:p.start,end_at:p.end,description:`Protected time. Primtal reference ${s.id}`,visibility:'private',attendees:[],auto_conference:false,auto_meeting_notes:false});}catch{p.status='uncertain';await persist(s);throw new Error('Calendar creation result is uncertain. Inspect the calendar; no automatic retry was made.');}p.eventId=created.id;p.status='created';s.stage='approved';await queue(s,`Created your one-hour focus event.\n[Open calendar](https://app.ambiguous.ai/calendar?event=${encodeURIComponent(created.id)})\n\nYou can undo this event below.`,[{label:'Undo this focus block',value:'UNDO'},...followupChoices(s)],'✓ Focus time protected');await saveCheckin(s);return;}
if(s.stage==='approved'&&command==='UNDO'){await undo(c,s);return;}await queue(s,s.stage==='safety'?'Calendar actions are paused. Please use the support options above. No person has been contacted.':'This check-in is finished. Start another from the Primtal panel.');}
export async function undo(c:Config,s:Session){
 const p=s.proposal;if(!p?.eventId||!applied(p))throw new Error('There is no confirmed calendar change to undo.');
 if(p.kind==='move'){
  try{await changeMeeting(c,p,true,async()=>{p.status='undoing';await persist(s);});p.status='undone';s.stage='complete';await queue(s,`Original meeting time restored.\n[Open meeting](https://app.ambiguous.ai/calendar?event=${p.eventId})`);await saveCheckin(s);}
  catch(e){if(p.status==='undoing')p.status='uncertain';await queue(s,p.status==='uncertain'?'The restore response was interrupted. Inspect the event before retrying.':e instanceof Error?e.message:'The meeting could not be restored.');}return;
 }
 await ownCalendar(c);const e=await amb(c.botKey,`/api/calendars/events/${p.eventId}`);if(e.calendar_id!==c.calendarId||!e.description?.includes(s.id))throw new Error('Event ownership check failed.');await amb(c.botKey,`/api/calendars/events/${p.eventId}`,'DELETE');p.status='undone';if(s.focus?.eventId===p.eventId)s.focus.status='undone';s.stage='complete';await queue(s,'Your Primtal focus event was removed. Other calendar events were kept.');await saveCheckin(s);
}
export async function tick(owner:string,c:Config){let s=await getSession(owner);if(s?.outbox&&s.outbox.state!=='sent'){await flush(c,s);return s;}if(c.enabled){const day=formatInTimeZone(new Date(),c.timezone,'yyyy-MM-dd');const clock=formatInTimeZone(new Date(),c.timezone,'HH:mm');if(clock>=c.hour&&c.lastDay!==day&&(!s||['complete','stopped','safety','approved'].includes(s.stage))){s=await start(owner,c,false);c.lastDay=day;await saveConfig(owner,c);}}
if(!s)return null;await assertDM(c);const vote=await selectedChoice(c,s.outbox);if(vote){await closeCard(c,s.outbox);await accept(c,s,vote.value);await persist(s);await flush(c,s);return s;}const r=await amb(c.botKey,`/api/channels/${c.channelId}/messages?limit=100${s.cursor?'&after='+encodeURIComponent(s.cursor):''}`);const incoming=(r.data||[]).filter((m:{author?:{id:string};created_at:string;deleted_at?:string;thread_id?:string})=>m.author?.id===c.userId&&!m.deleted_at&&!m.thread_id&&Date.parse(m.created_at)>=s.created).sort((a:{created_at:string;id:string},b:{created_at:string;id:string})=>Date.parse(a.created_at)-Date.parse(b.created_at)||a.id.localeCompare(b.id));for(const m of incoming.slice(0,1)){s.cursor=m.id;await closeCard(c,s.outbox);await accept(c,s,m.content);await persist(s);await flush(c,s);}return s;}
