import {z} from 'zod';
import {signedIn,myPerson} from '@/lib/primtal/web-auth';
import {bound,person,personConfig,savePerson} from '@/lib/primtal/participants';
import {connection} from '@/lib/primtal/connections';
import {DEFAULT_MODEL} from '@/lib/primtal/openrouter';
import {amb,ownCalendar} from '@/lib/primtal/ambiguous';
import {db,lock,errorResponse} from '@/lib/primtal/store';
import {start,getSession,accept,flush,tick,analyze} from '@/lib/primtal/workflow';
import {runOnce,runParticipant} from '@/lib/primtal/runner';
export const dynamic='force-dynamic';
export async function GET(request:Request){try{const user=await signedIn(request);const id=await bound(user.userId);const c=await connection();const model=c?.data.openrouterKey?(c.data.model||DEFAULT_MODEL):null;const heart=await db().prepare('SELECT value FROM settings WHERE id=?').bind('runner-heartbeat').first<{value:string}>();if(!id)return Response.json({paired:false,model,ready:!!c?.data.openrouterKey&&!!c.data.botId,heartbeat:heart?JSON.parse(heart.value).at:null},{headers:{'Cache-Control':'no-store'}});const p=await person(id);if(!p)return Response.json({paired:false});const s=await getSession(id);let calendars:{id:string;name:string;timezone:string}[]=[];let calendarError='';try{const cfg=await personConfig(id);const r=await amb(cfg.botKey,'/api/calendars');calendars=(r.data||[]).filter((v:{owner_id:string;workspace_id:string})=>v.owner_id===p.userId&&v.workspace_id===p.workspaceId).map((v:{id:string;name:string;timezone:string})=>({id:v.id,name:v.name,timezone:v.timezone}));}catch{calendarError='Your shared calendars could not be loaded.';}return Response.json({paired:true,name:p.name,model,ready:true,settings:{calendarId:p.calendarId,timezone:p.timezone,hour:p.hour,enabled:p.enabled,consent:p.consent},calendars,calendarError,heartbeat:heart?JSON.parse(heart.value).at:null,session:s?{id:s.id,stage:s.stage,index:s.index,demo:s.demo,summary:s.summary,proposal:s.proposal,prompt:s.outbox?.content||s.outbox?.question,choices:s.outbox?.choices,cardRef:s.outbox?.ref,error:s.error}:null},{headers:{'Cache-Control':'no-store'}});}catch(e){return errorResponse(e);}}
export async function POST(request:Request){try{const user=await signedIn(request);const input=z.object({action:z.enum(['start','poll','approve','skip','undo','stop','settings','answer','calendar']),value:z.string().max(100).optional(),cardRef:z.string().optional(),demo:z.boolean().optional(),consent:z.boolean().optional(),sessionId:z.string().optional(),calendarId:z.string().max(100).optional(),timezone:z.string().max(100).optional(),hour:z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).optional(),enabled:z.boolean().optional()}).strict().parse(await request.json());
 if(input.action==='poll'){const id=await bound(user.userId);if(id)await runParticipant(id);else {const c=await connection();if(c?.owner!==user.userId)throw new Error('Pairing is pending.');await runOnce();}return Response.json({ok:true});}
 const id=await myPerson(request);return await lock(id,async()=>{const p=await person(id);if(!p)throw new Error('Pair your account.');const c=await personConfig(id);
 if(input.action==='settings'){if(input.timezone)new Intl.DateTimeFormat('en',{timeZone:input.timezone});if(input.calendarId){const r=await amb(c.botKey,'/api/calendars');if(!r.data?.some((v:{id:string;owner_id:string;workspace_id:string})=>v.id===input.calendarId&&v.owner_id===p.userId&&v.workspace_id===p.workspaceId))throw new Error('Choose a calendar owned by your paired account.');}await savePerson(id,{...p,calendarId:input.calendarId??p.calendarId,timezone:input.timezone??p.timezone,hour:input.hour??p.hour,enabled:input.enabled??p.enabled,consent:input.consent??p.consent});return Response.json({ok:true});}
 if(input.action==='start'){if(input.consent!==true&&!p.consent)throw new Error('Confirm personal-data consent.');if(input.consent){p.consent=true;await savePerson(id,p);c.consent=true;}if(input.calendarId){c.calendarId=input.calendarId;await ownCalendar(c);}else await ownCalendar(c).catch(()=>{});if(input.timezone){new Intl.DateTimeFormat('en',{timeZone:input.timezone});c.timezone=input.timezone;}p.calendarId=c.calendarId;p.timezone=c.timezone;await savePerson(id,p);const s=await start(id,c,input.demo??true);return Response.json({ok:true,stage:s.stage});}
 const s=await getSession(id);if(!s||s.id!==input.sessionId)throw new Error('This check-in changed. Refresh before acting.');if(input.action==='calendar'){await analyze(c,s);await flush(c,s);return Response.json({ok:true});}if(input.action==='answer'){if(s.outbox?.ref!==input.cardRef||!s.outbox?.choices?.some(o=>o.value===input.value))throw new Error('That question has changed. Refresh to answer.');const {closeCard}=await import('@/lib/primtal/message-cards');await closeCard(c,s.outbox);await accept(c,s,input.value!);await flush(c,s);return Response.json({ok:true});}await accept(c,s,({approve:'APPROVE',skip:'SKIP',undo:'UNDO',stop:'STOP'} as Record<string,string>)[input.action]||'');if(input.action==='stop'){p.enabled=false;await savePerson(id,p);}await flush(c,s);return Response.json({ok:true});},10000);
 }catch(e){return errorResponse(e);}}
