'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
export default function HistoryPanel({name,onPrepared,onBusyChange}:{name:string;onPrepared:()=>void;onBusyChange:(value:boolean)=>void}){
 const [busy,setBusy]=useState(false),[message,setMessage]=useState(''),[days,setDays]=useState(0),[acknowledge,setAcknowledge]=useState(false);
 const refresh=()=>fetch('/api/history').then(r=>r.json()).then(d=>setDays((d as {days?:number}).days||0));useEffect(()=>{refresh().catch(()=>{});},[]);
 async function request(action:string,step?:number){const r=await fetch('/api/history',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,step,acknowledge:true})});const d=await r.json() as {error?:string;skipped?:number;removed?:number;created?:number};if(!r.ok)throw new Error(d.error||'Preparation failed.');return d;}
 async function prepare(){setBusy(true);onBusyChange(true);let prepared=0,skipped=0;try{for(let step=0;step<10;step++){setMessage(`Preparing past workday ${step+1} of 10…`);const r=await request('prepare',step);if(r.skipped)skipped++;else prepared++;}await refresh();onPrepared();setMessage(`${prepared} workdays prepared${skipped?`; ${skipped} skipped to preserve existing data`:''}. Use Review my calendar to see the comparison.`);}catch(e){setMessage((e as Error).message+' Completed days are saved; you can resume.');}finally{setBusy(false);onBusyChange(false);}}
 async function act(action:'clear'|'today'){setBusy(true);onBusyChange(true);try{const r=await request(action);await refresh();onPrepared();setMessage(action==='clear'?`${r.removed} synthetic answer records removed. Calendar events remain under your control.`:`${r.created} work events added for today; ${r.skipped} existing or conflicting slots kept.`);}catch(e){setMessage((e as Error).message);}finally{setBusy(false);onBusyChange(false);}}
 return <details className="history-setup"><summary><strong>Presentation setup</strong><span>{days} prepared days</span></summary><p>Prepare example history for <strong>{name}</strong>, the account paired with this panel.</p><div className="history-comparison"><div><strong>5 late-meeting days</strong><p>Lower mood and enjoyment. More fatigue and difficulty focusing.</p></div><div><strong>5 other workdays</strong><p>Higher mood and enjoyment. Less fatigue.</p></div></div><p className="muted">Adds synthetic answers and private calendar events for the last 10 workdays. Existing answers and conflicting events are preserved. The bot identifies prepared history when presenting the comparison.</p><label className="check"><input type="checkbox" checked={acknowledge} onChange={e=>setAcknowledge(e.target.checked)}/>I understand these are synthetic records for a presentation.</label><div className="row actions"><Button disabled={busy||!acknowledge} onClick={prepare}>Prepare 10 past workdays</Button><Button variant="outline" disabled={busy||!acknowledge} onClick={()=>act('today')}>Add work events for today</Button><Button variant="outline" disabled={busy||!acknowledge||!days} onClick={()=>act('clear')}>Remove synthetic answers</Button></div><p className="calendar-legend"><span aria-hidden="true"/>Purple events were created or changed with Primtal.</p>{message&&<p role="status">{message}</p>}</details>;
}
